### PR TITLE
fix: install tslib

### LINKED ISSUE #17: >=0.2.8 is broken with "Cannot find module 'tslib' "
Repro here https://github.com/Prinzhorn/parcel-pug-tslib

If you change the dependency in package.json to `"parcel-plugin-pug": "0.2.7"` it works.

Not sure what broke, I've looked through both 0.2.8 and 0.3.0 commits. Maybe a dependency?

I'm running node v8.9.4 and npm 5.8.0 rn

### PR DESCRIPTION
**Pull request by fathyb**
Fixes #17 and parcel-bundler/parcel#1077

### CODE REVIEW

**Comment by Ty3uK** [comment]
Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fathyb** [comment]
@Prinzhorn because `importHelpers` is set to `true` : https://github.com/Ty3uK/parcel-plugin-pug/blob/00b9cea75526137cbb5f792cc4fae202268f3a09/tsconfig.json#L14

From the [TypeScript docs](https://www.typescriptlang.org/docs/handbook/compiler-options.html) :

| Option          | Type    | Default | Description                                                    | 
|-----------------|---------|---------|----------------------------------------------------------------|
| `--importHelpers` | `boolean` | `false`   | Import emit helpers (e.g. `__extends`, `__rest`, etc..) from `tslib` |

**Comment by Prinzhorn** [comment]
@fathyb thanks, I've never used TypeScript and had no idea ;)

**Comment by Prinzhorn** [comment]
@Ty3uK can you publish this to npm as 0.3.1?

**Comment by Ty3uK** [comment]
@Prinzhorn yep, sorry :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ty3uK** [comment]
@Prinzhorn released, sorry for delay

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Prinzhorn** [comment]
@Ty3uK thanks, no worries

**Pull request merged**
