### PR TITLE
Fixed resolving dependencies inside tag attributes

### PR DESCRIPTION
**Pull request by dolma**
This PR is meant to fix the bug that occurred when using any kind of variable or interpolated string inside a tag attribute of types `src`, `href`, or `poster`.

Issue #10 is an example of this bug. In my case, it happened while trying to set an `href` attribute using a variable.

The build crash itself was caused by a lack of checking before adding the dependencies which resulted in Parcel trying to resolve a dependency that did not exist.

I added a regex to check whether the attribute value is actually a pure string or if it is a variable that needs to be evaluated first. The code now only adds the dependency if it's a pure string, which removes the crash.

However, this was not enough to fix the actual behaviour bug. The string now gets evaluated but if the results of the string interpolation is a resource then it is not added to the list of dependencies (since it's not a pure string) and the resource path is not replaced by the hash.

In order to do this while only being able to modify how `PugAsset.js` works, I added an extra step in case a non-pure attribute is detected during the dependency collection stage.

If so, `PugAsset.js` would first process the pug code by itself, which would generate html code.
Then, it will create an intermediate html asset from `HTMLAsset.js` using the generated html code and run its `process()` function (which will, among other things, collect the new interpolated dependencies and add them to the Parcel asset).

This was the only way I could think of to solve this bug without touching the Parcel or Pug files.

I also tried my best to adapt the TypeScript code to the new changes but please double check to see if I got any of them wrong.

### CODE REVIEW

**Comment by dolma** [comment]
Seems like it actually introduced a separate bug instead... So might not be safe to merge yet

**Comment by dolma** [comment]
Ok found a way around it, the problematic line was the piece of code replacing the attribute value with the hashed resolved path. Instead, we can let the HTMLAsset take care of it instead of doing it twice. The only downside is that the HTMLAsset process is run no matter if there were unresolved dependencies or not. Which might not be a big concern since there's a good chance most projects would have at least one variable attribute and thus run the HTMLAsset process anyway.
I'll recommit the new changes and remove the `hasUnresolvedDependencies` check/variable.

**Comment by dolma** [comment]
Actually might not need to do the resolving anymore either now that I think of it, since we're not using its result anywhere anymore.

**Comment by Ty3uK** [comment]
@dolma thanks for contributing , I’ll check it ASAP. 🤝

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dolma** [comment]
Thanks for replying so fast ! By the way, not sure if it's just a local issue or if it's linked to the changes(guessing the latter), but I noticed the hot reload didn't really run all the time, sometimes it stopped running after a few changes to the code and I had to stop the server and re-run parcel.

I added `htmlAsset.hash = this.hash;` in the `process()` function and it seems to solve it. The new function code:

```
async process() {
    await super.process();

    const htmlAsset = new HTMLAsset(this.name, this.package, this.options);
    htmlAsset.contents = this.generated.html;
    await htmlAsset.process();

    htmlAsset.hash = this.hash;

    Object.assign(this, htmlAsset);

    return this.generated;
}
```

I'm assuming it has something to do with parcel being lost between the hashes calculated by PugAsset and the ones calculated by HTMLAsset. By replacing the hash by the original one calculated by the PugAsset (with the line above), it seems to be solving it. At least so far it has been nicely running hot code reload every time.

**Comment by Ty3uK** [comment]
Merged, thanks for your contribution!

**Pull request merged**
